import Footer from '@/components/Footer';
import NavBar from '@/components/Navbar';
import { createSEOMetadata } from '@/lib/createSEOMetadata';
import localFont from 'next/font/local';
import './globals.css';
import { Metadata } from 'next';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = createSEOMetadata({
  title: {
    template: "%s | Noah's Utilities",
    default: 'Noah S Klinger Utilities',
  },
  description: 'Noah S Klinger Utilities - Generated by create next app',
  url: new URL(process.env.BASE_URL || 'https://noahsk23.github.io/utilities/'),
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex h-screen flex-col justify-between font-sans">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
