import Footer from '@/components/Footer';
import NavBar from '@/components/Navbar';
import { createSEOMetadata } from '@/lib/createSEOMetadata';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = createSEOMetadata({
  title: {
    template: "%s | Noah's Utilities",
    default: 'Noah S Klinger Utilities',
  },
  description: 'Noah S Klinger Utilities - Generated by create next app',
  url: new URL(process.env.BASE_URL || 'https://noahsk23.github.io/utilities/'),
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex min-h-screen flex-col justify-between font-sans">
        <NavBar />
        <div className="flex grow items-center justify-center bg-linear-to-b from-slate-200 to-slate-300 dark:from-slate-900 dark:to-slate-950">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
